### ISSUE TITLE
Custom SSH port

### ISSUE THREAD

**Issue by pjv** [521dimensions/ansible-postal#1]
Hi @jaydrogers,

Thanks so much for making this available.

If you change the SSH port in `group_vars/all` then running the playbook fails at:
`TASK [common : Enable UFW firewall]`

with the following:
`fatal: [send1.example.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host send1.example.com port 22: Operation timed out", "unreachable": true}`

I have never been able to figure out how to switch the SSH port successfully within a single playbook, so my own server setup is split into two playbooks. One is all the stuff that needs to happen before the port switch and the other is all the stuff that happens afterward. In that second playbook, I have:

```
vars:
      - ansible_port : "{{ ssh_port }}"
```

**Comment by jaydrogers** [comment]
Not sure if this is an SSH client configuration or not? 

**Some background**
I am running macOS 10.14.5 and it will get through all of it then restart the SSH service on the server at the end. This is where it applies my change.

I have to switch the username after the first provision (because I disable root login), but other than that I don't have any issues. I also have my `~/.ssh/config` set like this:

```
Host *.mydomain.test
        Port 1234
```

So I usually set the `ansible_port` like you have on the first run, then comment it out after that.

Hopefully this helps!

**Comment by jaydrogers** [comment]
Just letting you know that I tested it again with my macOS system. I was able to change the SSH port and it completed its run.

It wasn't until the end (after it completed everything and restarted the services) where I needed to add the options to my `~/.ssh/config` to get it to connect again (which is my expected result).

I would take a look in your client config and see if it is that. If you are on a different OS, it might just flat out behave differently too.

**Comment by pjv** [comment]
macOS 10.14.3, ansible 2.8.2.

On my next run of your playbook (moving back to DO from vultr who wouldn't let me send mail), I ran my own ubuntu setup playbook first which changes the port and sets up a non-root admin user. So then I changed your playbook to use my admin username and custom SSH port and it completed fine.
